# NumPy va Pandas bilan Ishlash

## Ma'ruza maqsadi
Bu ma'ruzada Python da ma'lumotlar tahlili uchun eng muhim kutubxonalar bilan tanishamiz:

### 📊 O'rganiladigan mavzular:
1. **NumPy** - Numerical Python (Arraylar bilan ishlash)
2. **Pandas** - Python Data Analysis Library (DataFrame va Series)
3. **Ma'lumotlarni yuklash va saqlash**
4. **Indexing, Filtering va Querying**
5. **Ma'lumotlarni tozalash va transformatsiya**
6. **Aggregation va Grouping**
7. **Ma'lumotlarni birlashtirish (Merging/Joining)**
8. **Amaliy misollar va real loyihalar**

---

### 🎯 Dars natijalari:
- NumPy arraylar bilan samarali ishlash
- Pandas DataFrame va Series tuzilmalarini boshqarish  
- Ma'lumotlarni filtrlash va qidirish
- Statistik tahlil va aggregatsiya
- Real ma'lumotlar bilan amaliy tajriba

---

## 1. NumPy (Numerical Python) asoslari

**NumPy** - Python da ilmiy hisoblash uchun asosiy kutubxona. U ko'p o'lchamli arraylar va ularga tegishli matematik funksiyalarni taqdim etadi.

### NumPy ning afzalliklari:
- **Tezlik**: C tilida yozilgan, juda tez
- **Memory efficiency**: Kam xotira ishlatadi
- **Broadcasting**: Turli o'lchamdagi arraylar bilan ishlash
- **Matematik funksiyalar**: Keng turdagi matematik operatsiyalar
- **Vektorlashtirish**: Loop'larsiz hisoblashlar

### Array vs Python List:
| Python List | NumPy Array |
|-------------|-------------|
| Turli data tiplar | Bir xil data tip |
| Sekin | Tez |
| Ko'p xotira | Kam xotira |
| Matematik amallar yo'q | Ko'plab matematik funksiyalar |

In [26]:
# NumPy kutubxonasini import qilish
import numpy as np
import time

print("🔢 NumPy bilan tanishish")
print("=" * 50)

# 1. NumPy versiyasini tekshirish
print(f"NumPy versiyasi: {np.__version__}")

# 2. Oddiy Python list vs NumPy array tezligini solishtirish
print("\n⚡ Tezlikni solishtirish:")

# Python list
python_list = list(range(1_000_000))
start_time = time.time()
result_list = [x * 2 for x in python_list]
python_time = time.time() - start_time

# NumPy array
numpy_array = np.arange(1_000_000)
start_time = time.time()
result_array = numpy_array * 2
numpy_time = time.time() - start_time

print(f"Python list: {python_time:.4f} sekund")
print(f"NumPy array: {numpy_time:.4f} sekund")
print(f"NumPy {python_time/numpy_time:.1f} marta tezroq!")

print("\n" + "=" * 50)

🔢 NumPy bilan tanishish
NumPy versiyasi: 1.26.4

⚡ Tezlikni solishtirish:
Python list: 0.0352 sekund
NumPy array: 0.0015 sekund
NumPy 24.1 marta tezroq!



### 1.1 NumPy Array yaratish usullari

NumPy arraylarni turli usullarda yaratish mumkin:

In [31]:
# NumPy array yaratish usullari

print("📦 NumPy Array yaratish")
print("=" * 50)

# 1. Oddiy listdan array yaratish
python_list = [1, 2, 3, 4, 5]
arr1 = np.array(python_list)
print(f"Listdan array: {arr1}")
print(f"Data tipi: {arr1.dtype}")
print(f"Shakli: {arr1.shape}")
print(f"O'lchamlari soni: {arr1.ndim}")

# 2. 2D array (matritsa)
matrix = np.array([
    [1, 2, 3], 
    [4, 5, 6], 
    [7, 8, 9]
])
print(f"\n2D Array:\n{matrix}")
print(f"Shakli: {matrix.shape}")
print(f"O'lchamlari soni: {matrix.ndim}")

# 3. Ma'lum qiymatlar bilan to'ldirilgan arraylar
zeros_arr = np.zeros((3, 4))  # Nollar bilan
ones_arr = np.ones((2, 3))    # Birlar bilan
full_arr = np.full((2, 2), 7) # Ma'lum qiymat bilan

print(f"\nNollar array:\n{zeros_arr}")
print(f"\nBirlar array:\n{ones_arr}")
print(f"\nTo'ldirilgan array:\n{full_arr}")

print("\n" + "=" * 50)

📦 NumPy Array yaratish
Listdan array: [1 2 3 4 5]
Data tipi: int64
Shakli: (5,)
O'lchamlari soni: 1

2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shakli: (3, 3)
O'lchamlari soni: 2

Nollar array:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Birlar array:
[[1. 1. 1.]
 [1. 1. 1.]]

To'ldirilgan array:
[[7 7]
 [7 7]]



In [ ]:
# Range va linspace bilan arraylar yaratish

print("📈 Range va Linspace")
print("=" * 50)

# 4. arange - Python range ga o'xshash
arr_range = np.arange(0, 10, 2)  # start, stop, step
print(f"arange(0, 10, 2): {arr_range}")

# 5. linspace - ma'lum oraliqda teng taqsimlangan qiymatlar
arr_linspace = np.linspace(0, 10, 11)  # start, stop, count
print(f"linspace(0, 10, 11): {arr_linspace}")

# 6. Tasodifiy arraylar
random_arr = np.random.random((2, 3))  # 0-1 orasida
randint_arr = np.random.randint(1, 100, (2, 4))  # 1-100 orasida butun sonlar
normal_arr = np.random.normal(0, 1, (3, 3))  # Normal taqsimot

print(f"\nTasodifiy array (0-1):\n{random_arr}")
print(f"\nTasodifiy butun sonlar (1-100):\n{randint_arr}")
print(f"\nNormal taqsimot:\n{normal_arr}")

# 7. Maxsus arraylar
identity = np.eye(3)  # Birlik matritsa
diagonal = np.diag([1, 2, 3, 4])  # Diagonal matritsa

print(f"\nBirlik matritsa:\n{identity}")
print(f"\nDiagonal matritsa:\n{diagonal}")

print("\n" + "=" * 50)

📈 Range va Linspace
arange(0, 10, 2): [0 2 4 6 8]
linspace(0, 10, 5): [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]

Tasodifiy array (0-1):
[[0.29563369 0.10549426 0.45653457]
 [0.21844044 0.41650995 0.88328026]]

Tasodifiy butun sonlar (1-100):
[[92 89 62 97]
 [ 1 27 62 77]]

Normal taqsimot:
[[-2.65517605  0.34551794 -0.39551645]
 [-0.28913686  0.45293633 -0.16606091]
 [ 0.21493883 -2.02231493 -0.94305681]]

Birlik matritsa:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Diagonal matritsa:
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]



### 1.2 Array Indexing va Slicing

NumPy arraylardan ma'lumotlarni olish va o'zgartirish:

In [40]:
# Array Indexing va Slicing

print("🎯 Array Indexing va Slicing")
print("=" * 50)

# 1D array bilan ishlash
arr_1d = np.array([10, 20, 30, 40, 50, 60, 70])
print(f"1D Array: {arr_1d}")
print(f"Birinchi element: {arr_1d[0]}")
print(f"Oxirgi element: {arr_1d[-1]}")
print(f"Slicing [1:5]: {arr_1d[1:5]}")
print(f"Har ikkinchi element: {arr_1d[::2]}")

# 2D array bilan ishlash
arr_2d = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8], 
                   [9, 10, 11, 12]])

print(f"\n2D Array:\n{arr_2d}")
print(f"Element [1, 2]: {arr_2d[1, 2]}")  # 2-qator, 3-ustun (0 dan boshlab)
print(f"Birinchi qator: {arr_2d[0, :]}")
print(f"Ikkinchi ustun: {arr_2d[:, 1]}")
print(f"2x2 subarray:\n{arr_2d[0:2, 1:3]}")

# Boolean indexing
arr = np.array([1, 5, 10, 15, 20, 25])
condition = arr > 10
print(f"\nArray: {arr}")
print(f"Condition (>10): {condition}")
print(f"Filtered array: {arr[condition]}")

# Fancy indexing
indices = [0, 4, 2, 5]
print(f"Fancy indexing {indices}: {arr[indices]}")

print("\n" + "=" * 50)

🎯 Array Indexing va Slicing
1D Array: [10 20 30 40 50 60 70]
Birinchi element: 10
Oxirgi element: 70
Slicing [1:5]: [20 30 40 50]
Har ikkinchi element: [10 30 50 70]

2D Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Element [1, 2]: 7
Birinchi qator: [1 2 3 4]
Ikkinchi ustun: [ 2  6 10]
2x2 subarray:
[[2 3]
 [6 7]]

Array: [ 1  5 10 15 20 25]
Condition (>10): [False False False  True  True  True]
Filtered array: [15 20 25]
Fancy indexing [0, 4, 2, 5]: [ 1 20 10 25]



### 1.3 Matematik operatsiyalar va Broadcasting

NumPy ning eng kuchli xususiyatlaridan biri - matematik operatsiyalarni vektorlashtirish:

In [42]:
# Matematik operatsiyalar va Broadcasting

print("🧮 Matematik operatsiyalar")
print("=" * 50)

# Asosiy matematik amallar
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])

print(f"a = {a}")
print(f"b = {b}")
print(f"a + b = {a + b}")
print(f"a - b = {a - b}")  
print(f"a * b = {a * b}")
print(f"a / b = {a / b}")
print(f"a ** 2 = {a ** 2}")

# Matematik funksiyalar
arr = np.array([1, 4, 9, 16, 25])
print(f"\nArray: {arr}")
print(f"sqrt: {np.sqrt(arr)}")
print(f"log: {np.log(arr)}")
print(f"sin: {np.sin(arr)}")
print(f"exp: {np.exp([1, 2, 3])}")

# Aggregation funksiyalar
data = np.random.randint(1, 100, 10)
print(f"\nTasodifiy data: {data}")
print(f"Sum: {np.sum(data)}")
print(f"Mean: {np.mean(data)}")
print(f"Std: {np.std(data)}")
print(f"Min: {np.min(data)}")
print(f"Max: {np.max(data)}")
print(f"Median: {np.median(data)}")

print("\n" + "=" * 50)

🧮 Matematik operatsiyalar
a = [1 2 3 4 5]
b = [10 20 30 40 50]
a + b = [11 22 33 44 55]
a - b = [ -9 -18 -27 -36 -45]
a * b = [ 10  40  90 160 250]
a / b = [0.1 0.1 0.1 0.1 0.1]
a ** 2 = [ 1  4  9 16 25]

Array: [ 1  4  9 16 25]
sqrt: [1. 2. 3. 4. 5.]
log: [0.         1.38629436 2.19722458 2.77258872 3.21887582]
sin: [ 0.84147098 -0.7568025   0.41211849 -0.28790332 -0.13235175]
exp: [ 2.71828183  7.3890561  20.08553692]

Tasodifiy data: [ 2 92 54 87 96 97  1 19  2 53]
Sum: 503
Mean: 50.3
Std: 39.30915923801984
Min: 1
Max: 97
Median: 53.5



In [44]:
# Broadcasting misollar

print("📡 Broadcasting")
print("=" * 50)

# Broadcasting - turli o'lchamdagi arraylar bilan ishlash
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

scalar = 10
vector = np.array([1, 2, 3])

print(f"Matrix:\n{matrix}")
print(f"Scalar: {scalar}")
print(f"Vector: {vector}")

# Scalar bilan broadcasting
result1 = matrix + scalar
print(f"\nMatrix + Scalar:\n{result1}")

# Vector bilan broadcasting
result2 = matrix + vector
print(f"\nMatrix + Vector:\n{result2}")

# Array manipulation
arr = np.array([[1, 2], [3, 4], [5, 6]])
print(f"\nOriginal array:\n{arr}")

# Reshape
reshaped = arr.reshape(2, 3)
print(f"Reshaped (2, 3):\n{reshaped}")

# Transpose
transposed = arr.T
print(f"Transposed:\n{transposed}")

# Flatten
flattened = arr.flatten()
print(f"Flattened: {flattened}")

print("\n" + "=" * 50)

📡 Broadcasting
Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Scalar: 10
Vector: [1 2 3]

Matrix + Scalar:
[[11 12 13]
 [14 15 16]
 [17 18 19]]

Matrix + Vector:
[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]

Original array:
[[1 2]
 [3 4]
 [5 6]]
Reshaped (2, 3):
[[1 2 3]
 [4 5 6]]
Transposed:
[[1 3 5]
 [2 4 6]]
Flattened: [1 2 3 4 5 6]



## 2. Pandas (Python Data Analysis Library)

**Pandas** - Python da ma'lumotlar tahlili uchun eng mashhur kutubxona. U strukturali ma'lumotlar bilan ishlash uchun kuchli vositalar taqdim etadi.

### Pandas ning asosiy tuzilmalari:
- **Series** - 1D labeled array (index bilan)
- **DataFrame** - 2D labeled array (jadval)

### Pandas ning afzalliklari:
- **Flexible ma'lumot strukturasi**: CSV, Excel, JSON, SQL va boshqalar
- **Missing data bilan ishlash**: NaN qiymatlarni boshqarish
- **Data alignment**: Avtomatik index bo'yicha hizalash
- **Kuchli grupplash**: GroupBy operatsiyalar
- **Time series**: Vaqt qatorlari bilan ishlash
- **Merging/Joining**: Ma'lumotlarni birlashtirish

In [46]:
# Pandas kutubxonasini import qilish
import pandas as pd

print("🐼 Pandas bilan tanishish")
print("=" * 50)

# Pandas versiyasini tekshirish
print(f"Pandas versiyasi: {pd.__version__}")

# 1. Series yaratish
print("\n📊 Series - 1D ma'lumot strukturasi")
series1 = pd.Series([10, 20, 30, 40, 50])
print("Oddiy Series:")
print(series1)

# Index bilan Series
series2 = pd.Series([10, 20, 30, 40, 50], 
                   index=['a', 'b', 'c', 'd', 'e'])
print("\nIndex bilan Series:")
print(series2)

# Dictionary dan Series  
data_dict = {'Ahmad': 85, 'Fatima': 92, 'Bobur': 78, 'Zarina': 96}
series3 = pd.Series(data_dict)
print("\nDictionary dan Series:")
print(series3)

# Series xususiyatlari
print(f"\nSeries qiymatlari: {series3.values}")
print(f"Series index: {series3.index}")
print(f"Series data tipi: {series3.dtype}")

print("\n" + "=" * 50)

🐼 Pandas bilan tanishish
Pandas versiyasi: 2.3.0

📊 Series - 1D ma'lumot strukturasi
Oddiy Series:
0    10
1    20
2    30
3    40
4    50
dtype: int64

Index bilan Series:
a    10
b    20
c    30
d    40
e    50
dtype: int64

Dictionary dan Series:
Ahmad     85
Fatima    92
Bobur     78
Zarina    96
dtype: int64

Series qiymatlari: [85 92 78 96]
Series index: Index(['Ahmad', 'Fatima', 'Bobur', 'Zarina'], dtype='object')
Series data tipi: int64



### 2.1 DataFrame - 2D ma'lumot strukturasi

DataFrame - Pandas ning eng muhim tuzilmasi, jadval ko'rinishidagi ma'lumotlar:

In [47]:
# DataFrame yaratish usullari

print("📋 DataFrame yaratish")
print("=" * 50)

# 1. Dictionary dan DataFrame
data = {
    'Ism': ['Ahmad', 'Fatima', 'Bobur', 'Zarina', 'Sardor'],
    'Yosh': [25, 22, 30, 27, 24],
    'Shahar': ['Toshkent', 'Samarqand', 'Buxoro', 'Andijon', 'Namangan'],
    'Maosh': [5000000, 4200000, 6500000, 4800000, 3800000]
}

df = pd.DataFrame(data)
print("Dictionary dan DataFrame:")
print(df)

# 2. DataFrame xususiyatlari
print(f"\nDataFrame shakli: {df.shape}")
print(f"Ustunlar: {df.columns.tolist()}")
print(f"Index: {df.index.tolist()}")
print(f"Data tiplari:\n{df.dtypes}")

# 3. DataFrame haqida umumiy ma'lumot
print("\n🔍 DataFrame.info():")
df.info()

# 4. Statistik ma'lumotlar
print("\n📈 DataFrame.describe():")
print(df.describe())

print("\n" + "=" * 50)

📋 DataFrame yaratish
Dictionary dan DataFrame:
      Ism  Yosh     Shahar    Maosh
0   Ahmad    25   Toshkent  5000000
1  Fatima    22  Samarqand  4200000
2   Bobur    30     Buxoro  6500000
3  Zarina    27    Andijon  4800000
4  Sardor    24   Namangan  3800000

DataFrame shakli: (5, 4)
Ustunlar: ['Ism', 'Yosh', 'Shahar', 'Maosh']
Index: [0, 1, 2, 3, 4]
Data tiplari:
Ism       object
Yosh       int64
Shahar    object
Maosh      int64
dtype: object

🔍 DataFrame.info():
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Ism     5 non-null      object
 1   Yosh    5 non-null      int64 
 2   Shahar  5 non-null      object
 3   Maosh   5 non-null      int64 
dtypes: int64(2), object(2)
memory usage: 292.0+ bytes

📈 DataFrame.describe():
           Yosh         Maosh
count   5.00000  5.000000e+00
mean   25.60000  4.860000e+06
std     3.04959  1.033441e+06
min    22.

### 2.2 Ma'lumotlarni fayldan yuklash

Real loyihalarda ma'lumotlar odatda fayllardan yuklanadi:

In [48]:
# Ma'lumotlarni fayldan yuklash

print("📁 Fayldan ma'lumot yuklash")
print("=" * 50)

# CSV faylni yuklash
try:
    # Xodimlar ma'lumotlari
    xodimlar = pd.read_csv('sample_data/xodimlar.csv')
    print("Xodimlar ma'lumotlari yuklandi:")
    print(xodimlar.head())  # Birinchi 5 qator
    
    print(f"\nDataFrame shakli: {xodimlar.shape}")
    print(f"Ustunlar: {xodimlar.columns.tolist()}")
    
    # Mahsulotlar ma'lumotlari
    mahsulotlar = pd.read_csv('sample_data/mahsulotlar.cs"v')
    print(f"\n\nMahsulotlar DataFrame shakli: {mahsulotlar.shape}")
    print("Mahsulotlar (oxirgi 3 qator):")
    print(mahsulotlar.tail(3))  # Oxirgi 3 qator
    
    # Talabalar ma'lumotlari
    talabalar = pd.read_csv('sample_data/talabalar.csv')
    print(f"\n\nTalabalar DataFrame shakli: {talabalar.shape}")
    print("Talabalar (tasodifiy 5 qator):")
    print(talabalar.sample(5))  # Tasodifiy 5 qator
    
except FileNotFoundError as e:
    print(f"Fayl topilmadi: {e}")
    print("Sample data yaratamiz...")
    
    # Agar fayllar yo'q bo'lsa, sample data yaratish
    sample_data = {
        'ism': ['Ahmad', 'Fatima', 'Bobur', 'Zarina'],
        'yosh': [25, 22, 30, 27],
        'maosh': [5000000, 4200000, 6500000, 4800000]
    }
    xodimlar = pd.DataFrame(sample_data)
    print("Sample DataFrame:")
    print(xodimlar)

print("\n" + "=" * 50)

📁 Fayldan ma'lumot yuklash
Xodimlar ma'lumotlari yuklandi:
   id               ism  yosh  jinsi     shahar    maosh     bo_lim  \
0   1     Ahmad Karimov    28  Erkak   Toshkent  8500000         IT   
1   2   Fotima Usmonova    25   Ayol  Samarqand  6200000  Marketing   
2   3     Bobur Rahimov    32  Erkak     Buxoro  9800000         IT   
3   4    Zarina Alimova    29   Ayol    Andijon  7200000         HR   
4   5  Sardor Toshmatov    26  Erkak   Namangan  5800000     Moliya   

   ish_tajribasi ta_lim  
0              5   Oliy  
1              3   Oliy  
2              8   Oliy  
3              6   Oliy  
4              4   Oliy  

DataFrame shakli: (20, 9)
Ustunlar: ['id', 'ism', 'yosh', 'jinsi', 'shahar', 'maosh', 'bo_lim', 'ish_tajribasi', 'ta_lim']
Fayl topilmadi: [Errno 2] No such file or directory: 'sample_data/mahsulotlar.cs"v'
Sample data yaratamiz...
Sample DataFrame:
      ism  yosh    maosh
0   Ahmad    25  5000000
1  Fatima    22  4200000
2   Bobur    30  6500000
3  Zari

### 2.3 DataFrame Indexing va Selecting

DataFrame dan ma'lumotlarni turli usullarda olish:

In [50]:
# DataFrame Indexing va Selecting

print("🎯 DataFrame dan ma'lumot olish")
print("=" * 50)

# Sample DataFrame yaratish
data = {
    'Ism': ['Ahmad', 'Fatima', 'Bobur', 'Zarina', 'Sardor', 'Dilnoza'],
    'Yosh': [25, 22, 30, 27, 24, 26],
    'Shahar': ['Toshkent', 'Samarqand', 'Buxoro', 'Andijon', 'Namangan', 'Farg\'ona'],
    'Maosh': [5000000, 4200000, 6500000, 4800000, 3800000, 5200000],
    'Bolim': ['IT', 'HR', 'IT', 'Marketing', 'Moliya', 'IT']
}
df = pd.DataFrame(data)
print("Sample DataFrame:")
print(df)

# 1. Ustunlarni tanlash
print("\n📋 Ustun tanlash:")
print("Ism ustuni:")
print("type of df['Ism']:", type(df['Ism']))
print(df['Ism'])

print("\nBir nechta ustun:")
print(df[['Ism', 'Maosh']])

# 2. loc va iloc
print("\n🔍 loc va iloc:")
print("loc[0] - birinchi qator:")
print(df.loc[0])

print("\niloc[1:3] - 1-3 qatorlar:")
print(df.iloc[1:3])

print("\nloc[0:2, 'Ism':'Shahar'] - qatorlar va ustunlar:")
print(df.loc[0:2, 'Ism':'Shahar'])

# 3. Boolean indexing
print("\n✅ Boolean indexing:")
print("Yoshi 25 dan katta bo'lgan xodimlar:")
yosh_filtr = df['Yosh'] > 25
print(yosh_filtr)
print(df[yosh_filtr])

print("\nIT bo'limidagi xodimlar:")
it_xodimlar = df[df['Bolim'] == 'IT']
print(it_xodimlar)

print("\n" + "=" * 50)

🎯 DataFrame dan ma'lumot olish
Sample DataFrame:
       Ism  Yosh     Shahar    Maosh      Bolim
0    Ahmad    25   Toshkent  5000000         IT
1   Fatima    22  Samarqand  4200000         HR
2    Bobur    30     Buxoro  6500000         IT
3   Zarina    27    Andijon  4800000  Marketing
4   Sardor    24   Namangan  3800000     Moliya
5  Dilnoza    26   Farg'ona  5200000         IT

📋 Ustun tanlash:
Ism ustuni:
type of df['Ism']: <class 'pandas.core.series.Series'>
0      Ahmad
1     Fatima
2      Bobur
3     Zarina
4     Sardor
5    Dilnoza
Name: Ism, dtype: object

Bir nechta ustun:
       Ism    Maosh
0    Ahmad  5000000
1   Fatima  4200000
2    Bobur  6500000
3   Zarina  4800000
4   Sardor  3800000
5  Dilnoza  5200000

🔍 loc va iloc:
loc[0] - birinchi qator:
Ism          Ahmad
Yosh            25
Shahar    Toshkent
Maosh      5000000
Bolim           IT
Name: 0, dtype: object

iloc[1:3] - 1-3 qatorlar:
      Ism  Yosh     Shahar    Maosh Bolim
1  Fatima    22  Samarqand  4200000    H

### 2.4 Filtering va Querying

Ma'lumotlarni filtrlash va qidirish uchun kuchli vositalar:

In [51]:
# Advanced Filtering va Querying

print("🔎 Advanced Filtering")
print("=" * 50)

# Murakkab shartlar
print("Murakkab shartlar:")

# AND operatori
print("\nYoshi 24-27 orasida VA IT bo'limida:")
murakkab_filtr = (df['Yosh'] >= 24) & (df['Yosh'] <= 27) & (df['Bolim'] == 'IT')
print(df[murakkab_filtr])

# OR operatori  
print("\nToshkent yoki Samarqand shahrida:")
shahar_filtr = (df['Shahar'] == 'Toshkent') | (df['Shahar'] == 'Samarqand')
print(df[shahar_filtr])

# isin() method - ro'yxatdagi qiymatlar
print("\nMa'lum shaharlar ro'yxati:")
tanlangan_shaharlar = ['Toshkent', 'Buxoro', 'Andijon']
print(df[df['Shahar'].isin(tanlangan_shaharlar)])

# query() method - SQL kabi sintaksis
print("\nquery() method:")
print("Maoshi 4500000 dan yuqori:")
print(df.query('Maosh > 4500000'))

print("\nquery() murakkab shart:")
print(df.query("Yosh > 24 and 'Bolim' == 'IT'"))

# String operatsiyalar
print("\nString contains:")
a_harfi = df[df['Ism'].str.contains('a', case=False)]
print("Ismida 'a' harfi bor:")
print(a_harfi)

print("\n" + "=" * 50)

🔎 Advanced Filtering
Murakkab shartlar:

Yoshi 24-27 orasida VA IT bo'limida:
       Ism  Yosh    Shahar    Maosh Bolim
0    Ahmad    25  Toshkent  5000000    IT
5  Dilnoza    26  Farg'ona  5200000    IT

Toshkent yoki Samarqand shahrida:
      Ism  Yosh     Shahar    Maosh Bolim
0   Ahmad    25   Toshkent  5000000    IT
1  Fatima    22  Samarqand  4200000    HR

Ma'lum shaharlar ro'yxati:
      Ism  Yosh    Shahar    Maosh      Bolim
0   Ahmad    25  Toshkent  5000000         IT
2   Bobur    30    Buxoro  6500000         IT
3  Zarina    27   Andijon  4800000  Marketing

query() method:
Maoshi 4500000 dan yuqori:
       Ism  Yosh    Shahar    Maosh      Bolim
0    Ahmad    25  Toshkent  5000000         IT
2    Bobur    30    Buxoro  6500000         IT
3   Zarina    27   Andijon  4800000  Marketing
5  Dilnoza    26  Farg'ona  5200000         IT

query() murakkab shart:
Empty DataFrame
Columns: [Ism, Yosh, Shahar, Maosh, Bolim]
Index: []

String contains:
Ismida 'a' harfi bor:
       Ism

### 2.5 Data Cleaning va Transformation

Real ma'lumotlar bilan ishlashda eng muhim bosqich - ma'lumotlarni tozalash:

In [ ]:
# Data Cleaning va Transformation

print("🧹 Ma'lumotlarni tozalash")
print("=" * 50)

# Missing values bilan sample data yaratish
import numpy as np

messy_data = {
    'Ism': ['Ahmad', 'Fatima', np.nan, 'Zarina', 'Sardor', 'Dilnoza'],
    'Yosh': [25, np.nan, 30, 27, 24, 26],
    'Maosh': [5000000, 4200000, 6500000, np.nan, 3800000, 5200000],
    'Email': ['ahmad@mail.com', 'FATIMA@MAIL.COM', 'bobur@mail.com', 
              'zarina@mail.com', None, 'dilnoza@mail.com']
}

df_messy = pd.DataFrame(messy_data)
print("Asl ma'lumotlar (missing values bilan):")
print(df_messy)

# 1. Missing values tekshirish
print(f"\n🔍 Missing values tekshirish:")
print("isnull() - har bir element:")
print(df_messy.isnull())

print("\nHar ustundagi missing values soni:")
print(df_messy.isnull().sum())

# 2. Missing values bilan ishlash
print("\n🔧 Missing values bilan ishlash:")

# dropna() - missing values ni o'chirish
df_dropped = df_messy.dropna()
print("dropna() dan keyin:")
print(df_dropped)

# fillna() - missing values ni to'ldirish
df_filled = df_messy.copy()
df_filled['Yosh'].fillna(df_filled['Yosh'].mean(), inplace=True)  # O'rtacha bilan
df_filled['Maosh'].fillna(0, inplace=True)  # 0 bilan
df_filled['Ism'].fillna('Unknown', inplace=True)  # String bilan

print("\nfillna() dan keyin:")
print(df_filled)

print("\n" + "=" * 50)

🧹 Ma'lumotlarni tozalash
Asl ma'lumotlar (missing values bilan):
       Ism  Yosh      Maosh             Email
0    Ahmad  25.0  5000000.0    ahmad@mail.com
1   Fatima   NaN  4200000.0   FATIMA@MAIL.COM
2      NaN  30.0  6500000.0    bobur@mail.com
3   Zarina  27.0        NaN   zarina@mail.com
4   Sardor  24.0  3800000.0              None
5  Dilnoza  26.0  5200000.0  dilnoza@mail.com

🔍 Missing values tekshirish:
isnull() - har bir element:
     Ism   Yosh  Maosh  Email
0  False  False  False  False
1  False   True  False  False
2   True  False  False  False
3  False  False   True  False
4  False  False  False   True
5  False  False  False  False

Har ustundagi missing values soni:
Ism      1
Yosh     1
Maosh    1
Email    1
dtype: int64

🔧 Missing values bilan ishlash:
dropna() dan keyin:
       Ism  Yosh      Maosh             Email
0    Ahmad  25.0  5000000.0    ahmad@mail.com
5  Dilnoza  26.0  5200000.0  dilnoza@mail.com

fillna() dan keyin:
       Ism  Yosh      Maosh             

/var/folders/kp/_7qjsy8s0lg8j_3vqs3w_jzm0000gn/T/ipykernel_21276/269272995.py:39: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_filled['Yosh'].fillna(df_filled['Yosh'].mean(), inplace=True)  # O'rtacha bilan
/var/folders/kp/_7qjsy8s0lg8j_3vqs3w_jzm0000gn/T/ipykernel_21276/269272995.py:40: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object o

In [55]:
# Data Transformation

print("🔄 Ma'lumotlarni o'zgartirish")
print("=" * 50)

# Toza ma'lumotlar bilan ishlash
clean_data = {
    'Ism': ['Ahmad', 'Fatima', 'Bobur', 'Zarina', 'Sardor'],
    'Yosh': [25, 22, 30, 27, 24],
    'Maosh': [5000000, 4200000, 6500000, 4800000, 3800000]
}
df_clean = pd.DataFrame(clean_data)

# 1. Yangi ustun qo'shish
df_clean['Maosh_USD'] = df_clean['Maosh'] / 12100  # So'mdan dollarga
df_clean['Yosh_Kategoriya'] = df_clean['Yosh'].apply(
    lambda x: 'Yosh' if x < 25 else 'O\'rta' if x < 30 else 'Katta'
)

print("Yangi ustunlar qo'shilgan:")
print(df_clean)

# 2. String operatsiyalar
df_clean['Ism_Katta'] = df_clean['Ism'].str.upper()
df_clean['Ism_Uzunlik'] = df_clean['Ism'].str.len()
df_clean['Ism_Qisqa'] = df_clean['Ism'].str.slice(0, 3)

print(f"\nString operatsiyalardan keyin:")
print(df_clean[['Ism', 'Ism_Katta', 'Ism_Uzunlik']])

# 3. Apply funksiyasi
def yosh_status(yosh):
    if yosh < 25:
        return "Yosh professional"
    elif yosh < 30:
        return "Tajribali"
    else:
        return "Senior"

df_clean['Status'] = df_clean['Yosh'].apply(yosh_status)
print(f"\nApply funksiyasi natijasi:")
print(df_clean[['Ism', 'Yosh', 'Status']])

# 4. Map funksiyasi
yosh_mapping = {25: 'A', 22: 'B', 30: 'C', 27: 'D', 24: 'E'}
df_clean['Yosh_Kod'] = df_clean['Yosh'].map(yosh_mapping)
print(f"\nMap funksiyasi natijasi:")
print(df_clean[['Yosh', 'Yosh_Kod']])

print("\n" + "=" * 50)

🔄 Ma'lumotlarni o'zgartirish
Yangi ustunlar qo'shilgan:
      Ism  Yosh    Maosh   Maosh_USD Yosh_Kategoriya
0   Ahmad    25  5000000  413.223140           O'rta
1  Fatima    22  4200000  347.107438            Yosh
2   Bobur    30  6500000  537.190083           Katta
3  Zarina    27  4800000  396.694215           O'rta
4  Sardor    24  3800000  314.049587            Yosh

String operatsiyalardan keyin:
      Ism Ism_Katta  Ism_Uzunlik
0   Ahmad     AHMAD            5
1  Fatima    FATIMA            6
2   Bobur     BOBUR            5
3  Zarina    ZARINA            6
4  Sardor    SARDOR            6

Apply funksiyasi natijasi:
      Ism  Yosh             Status
0   Ahmad    25          Tajribali
1  Fatima    22  Yosh professional
2   Bobur    30             Senior
3  Zarina    27          Tajribali
4  Sardor    24  Yosh professional

Map funksiyasi natijasi:
   Yosh Yosh_Kod
0    25        A
1    22        B
2    30        C
3    27        D
4    24        E



### 2.6 Grouping va Aggregation

Ma'lumotlarni guruhlash va jamlovchi statistikalar hisoblash:

In [59]:
# Grouping va Aggregation

print("📊 Grouping va Aggregation")
print("=" * 50)

# Katta sample data yaratish
np.random.seed(42)
group_data = {
    'Xodim': [f'Xodim_{i}' for i in range(1, 21)],
    'Bo_lim': np.random.choice(['IT', 'HR', 'Marketing', 'Moliya'], 20),
    'Shahar': np.random.choice(['Toshkent', 'Samarqand', 'Buxoro'], 20),
    'Yosh': np.random.randint(22, 40, 20),
    'Maosh': np.random.randint(3000000, 10000000, 20),
    'Tajriba': np.random.randint(1, 15, 20)
}

df_group = pd.DataFrame(group_data)
print("Sample data:")
print(df_group.head(10))

# 1. Oddiy groupby
print(f"\n🔤 Bo'lim bo'yicha groupby:")
bolim_group = df_group.groupby('Bo_lim')
print("Bo'lim bo'yicha o'rtacha maosh:")
print(bolim_group['Maosh'].mean())

print("\nBo'lim bo'yicha statistikalar:")
print(bolim_group['Maosh'].agg(['count', 'mean', 'min', 'max', 'std']))

# 2. Multiple columns groupby
print(f"\n🏢 Bo'lim va Shahar bo'yicha:")
multi_group = df_group.groupby(['Bo_lim', 'Shahar'])
print("Bo'lim va Shahar bo'yicha o'rtacha maosh:")
print(multi_group['Maosh'].mean())

# 3. Aggregation funksiyalar
print(f"\n📈 Aggregation funksiyalar:")
agg_result = df_group.groupby('Bo_lim').agg({
    'Maosh': ['mean', 'min', 'max'],
    'Yosh': ['mean', 'count'],
    'Tajriba': 'sum'
})
print(agg_result)

print("\n" + "=" * 50)

📊 Grouping va Aggregation
Sample data:
      Xodim     Bo_lim     Shahar  Yosh    Maosh  Tajriba
0   Xodim_1  Marketing  Samarqand    36  4870928        8
1   Xodim_2     Moliya   Toshkent    33  7155299       14
2   Xodim_3         IT  Samarqand    24  5557489        7
3   Xodim_4  Marketing  Samarqand    26  4773415       12
4   Xodim_5  Marketing  Samarqand    28  9249859        9
5   Xodim_6     Moliya  Samarqand    30  8000193       14
6   Xodim_7         IT   Toshkent    28  8702653        8
7   Xodim_8         IT   Toshkent    39  5305413        5
8   Xodim_9  Marketing  Samarqand    25  6910197       13
9  Xodim_10         HR  Samarqand    35  8558019        2

🔤 Bo'lim bo'yicha groupby:
Bo'lim bo'yicha o'rtacha maosh:
Bo_lim
HR           8.558019e+06
IT           5.690581e+06
Marketing    5.913105e+06
Moliya       6.192415e+06
Name: Maosh, dtype: float64

Bo'lim bo'yicha statistikalar:
           count          mean      min      max           std
Bo_lim                       

### 2.7 Merging va Joining

Bir nechta DataFrame ni birlashtirish uchun kuchli vositalar:

In [60]:
# Merging va Joining

print("🔗 Ma'lumotlarni birlashtirish")
print("=" * 50)

# Sample DataFrames yaratish
xodimlar_info = pd.DataFrame({
    'ID': [1, 2, 3, 4, 5],
    'Ism': ['Ahmad', 'Fatima', 'Bobur', 'Zarina', 'Sardor'],
    'Bo_lim': ['IT', 'HR', 'IT', 'Marketing', 'Moliya']
})

maosh_info = pd.DataFrame({
    'ID': [1, 2, 3, 4, 6],  # 5 yo'q, 6 qo'shimcha
    'Maosh': [5000000, 4200000, 6500000, 4800000, 3500000],
    'Bonus': [500000, 200000, 800000, 300000, 100000]
})

print("Xodimlar ma'lumotlari:")
print(xodimlar_info)
print("\nMaosh ma'lumotlari:")
print(maosh_info)

# 1. Inner join (faqat umumiy qatorlar)
print(f"\n🎯 Inner join:")
inner_result = pd.merge(xodimlar_info, maosh_info, on='ID', how='inner')
print(inner_result)

# 2. Left join (chap DataFrame barcha qatorlari)
print(f"\n⬅️ Left join:")
left_result = pd.merge(xodimlar_info, maosh_info, on='ID', how='left')
print(left_result)

# 3. Right join (o'ng DataFrame barcha qatorlari)
print(f"\n➡️ Right join:")
right_result = pd.merge(xodimlar_info, maosh_info, on='ID', how='right')
print(right_result)

# 4. Outer join (barcha qatorlar)
print(f"\n🔄 Outer join:")
outer_result = pd.merge(xodimlar_info, maosh_info, on='ID', how='outer')
print(outer_result)

print("\n" + "=" * 50)

🔗 Ma'lumotlarni birlashtirish
Xodimlar ma'lumotlari:
   ID     Ism     Bo_lim
0   1   Ahmad         IT
1   2  Fatima         HR
2   3   Bobur         IT
3   4  Zarina  Marketing
4   5  Sardor     Moliya

Maosh ma'lumotlari:
   ID    Maosh   Bonus
0   1  5000000  500000
1   2  4200000  200000
2   3  6500000  800000
3   4  4800000  300000
4   6  3500000  100000

🎯 Inner join:
   ID     Ism     Bo_lim    Maosh   Bonus
0   1   Ahmad         IT  5000000  500000
1   2  Fatima         HR  4200000  200000
2   3   Bobur         IT  6500000  800000
3   4  Zarina  Marketing  4800000  300000

⬅️ Left join:
   ID     Ism     Bo_lim      Maosh     Bonus
0   1   Ahmad         IT  5000000.0  500000.0
1   2  Fatima         HR  4200000.0  200000.0
2   3   Bobur         IT  6500000.0  800000.0
3   4  Zarina  Marketing  4800000.0  300000.0
4   5  Sardor     Moliya        NaN       NaN

➡️ Right join:
   ID     Ism     Bo_lim    Maosh   Bonus
0   1   Ahmad         IT  5000000  500000
1   2  Fatima         

In [63]:
# Concat va boshqa birlashtirish usullari

print("📚 Concat va boshqa usullar")
print("=" * 50)

# Concat uchun sample data
df1 = pd.DataFrame({
    'A': [1, 2, 3],
    'B': [4, 5, 6]
})

df2 = pd.DataFrame({
    'A': [7, 8, 9],
    'B': [10, 11, 12]
})

df3 = pd.DataFrame({
    'C': [13, 14, 15],
    'D': [16, 17, 18]
})

print("DataFrame 1:")
print(df1)
print("\nDataFrame 2:")
print(df2)
print("\nDataFrame 3:")
print(df3)

# 1. Vertical concat (qatorlarni birlashtirish)
print(f"\n⬇️ Vertical concat (axis=0):")
vertical_concat = pd.concat([df1, df2], axis=0, ignore_index=True)
print(vertical_concat)

# 2. Horizontal concat (ustunlarni birlashtirish)
print(f"\n➡️ Horizontal concat (axis=1):")
horizontal_concat = pd.concat([df1, df3], axis=1)
print(horizontal_concat)

# Keys bilan concat
print(f"\n🔑 Keys bilan concat:")
keyed_concat = pd.concat([df1, df2], keys=['Group1', 'Group2'])
print(keyed_concat)

print("\n" + "=" * 50)

📚 Concat va boshqa usullar
DataFrame 1:
   A  B
0  1  4
1  2  5
2  3  6

DataFrame 2:
   A   B
0  7  10
1  8  11
2  9  12

DataFrame 3:
    C   D
0  13  16
1  14  17
2  15  18

⬇️ Vertical concat (axis=0):
   A   B
0  1   4
1  2   5
2  3   6
3  7  10
4  8  11
5  9  12

➡️ Horizontal concat (axis=1):
   A  B   C   D
0  1  4  13  16
1  2  5  14  17
2  3  6  15  18

🔑 Keys bilan concat:
          A   B
Group1 0  1   4
       1  2   5
       2  3   6
Group2 0  7  10
       1  8  11
       2  9  12



### 2.8 Pivot Tables va Cross-tabulation

Ma'lumotlarni qayta tashkil etish va pivot jadvallar yaratish:

In [64]:
# Pivot Tables va Cross-tabulation

print("🔄 Pivot Tables")
print("=" * 50)

# Pivot uchun sample data
sales_data = pd.DataFrame({
    'Sana': pd.date_range('2024-01-01', periods=12, freq='M'),
    'Sotuvchi': ['Ahmad', 'Fatima', 'Bobur', 'Ahmad', 'Fatima', 'Bobur'] * 2,
    'Mahsulot': ['Laptop', 'Phone', 'Laptop', 'Phone', 'Tablet', 'Tablet'] * 2,
    'Sotuv': [15000, 12000, 18000, 14000, 8000, 9000, 16000, 13000, 19000, 15000, 8500, 9500],
    'Miqdor': [5, 8, 3, 6, 10, 12, 4, 7, 2, 5, 15, 18]
})

print("Sotuv ma'lumotlari:")
print(sales_data.head(8))

# 1. Pivot table yaratish
print(f"\n📊 Pivot table - Sotuvchi va Mahsulot bo'yicha:")
pivot_table = pd.pivot_table(
    sales_data, 
    values='Sotuv', 
    index='Sotuvchi', 
    columns='Mahsulot', 
    aggfunc='mean',
    fill_value=0
)
print(pivot_table)

# 2. Multiple aggregation
print(f"\n📈 Multiple aggregation:")
multi_agg_pivot = pd.pivot_table(
    sales_data,
    values=['Sotuv', 'Miqdor'],
    index='Sotuvchi',
    columns='Mahsulot',
    aggfunc={'Sotuv': 'sum', 'Miqdor': 'mean'},
    fill_value=0
)
print(multi_agg_pivot)

# 3. Crosstab
print(f"\n🔀 Crosstab:")
crosstab_result = pd.crosstab(
    sales_data['Sotuvchi'], 
    sales_data['Mahsulot'], 
    values=sales_data['Sotuv'], 
    aggfunc='sum'
).fillna(0)
print(crosstab_result)

# 4. Melt - wide to long format
print(f"\n🫠 Melt - Pivot ning teskarisi:")
melted_data = pivot_table.reset_index().melt(
    id_vars='Sotuvchi',
    var_name='Mahsulot',
    value_name='O_rtacha_Sotuv'
)
print(melted_data)

print("\n" + "=" * 50)

🔄 Pivot Tables
Sotuv ma'lumotlari:
        Sana Sotuvchi Mahsulot  Sotuv  Miqdor
0 2024-01-31    Ahmad   Laptop  15000       5
1 2024-02-29   Fatima    Phone  12000       8
2 2024-03-31    Bobur   Laptop  18000       3
3 2024-04-30    Ahmad    Phone  14000       6
4 2024-05-31   Fatima   Tablet   8000      10
5 2024-06-30    Bobur   Tablet   9000      12
6 2024-07-31    Ahmad   Laptop  16000       4
7 2024-08-31   Fatima    Phone  13000       7

📊 Pivot table - Sotuvchi va Mahsulot bo'yicha:
Mahsulot   Laptop    Phone  Tablet
Sotuvchi                          
Ahmad     15500.0  14500.0     0.0
Bobur     18500.0      0.0  9250.0
Fatima        0.0  12500.0  8250.0

📈 Multiple aggregation:
         Miqdor               Sotuv              
Mahsulot Laptop Phone Tablet Laptop  Phone Tablet
Sotuvchi                                         
Ahmad       4.5   5.5    0.0  31000  29000      0
Bobur       2.5   0.0   15.0  37000      0  18500
Fatima      0.0   7.5   12.5      0  25000  16500

🔀 

/var/folders/kp/_7qjsy8s0lg8j_3vqs3w_jzm0000gn/T/ipykernel_21276/7006815.py:8: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  'Sana': pd.date_range('2024-01-01', periods=12, freq='M'),


## 3. Real Loyiha - Ma'lumotlar Tahlili

Haqiqiy ma'lumotlar bilan to'liq tahlil misoli:

In [ ]:
# Real loyiha - Xodimlar ma'lumotlari tahlili

print("🏢 Real loyiha: Xodimlar tahlili")
print("=" * 70)

# Katta dataset yaratish
np.random.seed(42)
n_employees = 100

# Realistic data yaratish
departments = ['IT', 'HR', 'Marketing', 'Moliya', 'Sotish', 'Operatsiya']
cities = ['Toshkent', 'Samarqand', 'Buxoro', 'Andijon', 'Namangan', 'Farg\'ona']
education_levels = ['O\'rta-maxsus', 'Oliy', 'Magistr', 'PhD']

employee_data = {
    'ID': range(1, n_employees + 1),
    'Ism': [f'Xodim_{i}' for i in range(1, n_employees + 1)],
    'Yosh': np.random.normal(30, 5, n_employees).astype(int),
    'Jinsi': np.random.choice(['Erkak', 'Ayol'], n_employees, p=[0.6, 0.4]),
    'Bo_lim': np.random.choice(departments, n_employees),
    'Shahar': np.random.choice(cities, n_employees),
    'Ta_lim': np.random.choice(education_levels, n_employees, p=[0.1, 0.6, 0.25, 0.05]),
    'Tajriba_yil': np.random.exponential(3, n_employees).astype(int),
    'Maosh': np.random.normal(6000000, 2000000, n_employees).astype(int),
    'Baho': np.random.normal(4.0, 0.5, n_employees).round(1)
}

# Yosh va tajribani realistik qilish
employee_data['Yosh'] = np.clip(employee_data['Yosh'], 22, 65)
employee_data['Tajriba_yil'] = np.clip(employee_data['Tajriba_yil'], 0, employee_data['Yosh'] - 22)
employee_data['Maosh'] = np.clip(employee_data['Maosh'], 3000000, 15000000)
employee_data['Baho'] = np.clip(employee_data['Baho'], 1.0, 5.0)

df_employees = pd.DataFrame(employee_data)

print("Dataset haqida ma'lumot:")
print(f"Jami xodimlar: {len(df_employees)}")
print(f"Ustunlar soni: {len(df_employees.columns)}")
print("\nBirinchi 5 qator:")
print(df_employees.head())

print("\n" + "=" * 70)

In [ ]:
# Exploratory Data Analysis (EDA)

print("🔍 Exploratory Data Analysis")
print("=" * 70)

# 1. Asosiy statistikalar
print("1️⃣ Asosiy statistikalar:")
print(df_employees.describe())

# 2. Categorical ma'lumotlar tahlili
print(f"\n2️⃣ Bo'limlar bo'yicha taqsimot:")
print(df_employees['Bo_lim'].value_counts())

print(f"\n3️⃣ Jins bo'yicha taqsimot:")
print(df_employees['Jinsi'].value_counts())

print(f"\n4️⃣ Ta'lim darajasi bo'yicha:")
print(df_employees['Ta_lim'].value_counts())

# 3. Bo'lim bo'yicha tahlil
print(f"\n5️⃣ Bo'limlar bo'yicha o'rtacha maosh:")
department_analysis = df_employees.groupby('Bo_lim').agg({
    'Maosh': ['mean', 'median', 'std', 'count'],
    'Yosh': 'mean',
    'Tajriba_yil': 'mean',
    'Baho': 'mean'
}).round(0)

print(department_analysis)

# 4. Jins bo'yicha tahlil
print(f"\n6️⃣ Gender analysis:")
gender_analysis = df_employees.groupby('Jinsi').agg({
    'Maosh': 'mean',
    'Yosh': 'mean',
    'Baho': 'mean'
}).round(0)
print(gender_analysis)

print("\n" + "=" * 70)

In [ ]:
# Advanced tahlil va Insights

print("🎯 Advanced Analysis va Insights")
print("=" * 70)

# 1. High earners tahlili
print("1️⃣ Top 10 eng yuqori maoshli xodimlar:")
top_earners = df_employees.nlargest(10, 'Maosh')[['Ism', 'Bo_lim', 'Yosh', 'Tajriba_yil', 'Maosh', 'Baho']]
print(top_earners)

# 2. Correlation tahlili
print(f"\n2️⃣ Raqamli o'zgaruvchilar orasidagi korrelyatsiya:")
numeric_cols = ['Yosh', 'Tajriba_yil', 'Maosh', 'Baho']
correlation_matrix = df_employees[numeric_cols].corr()
print(correlation_matrix.round(3))

# 3. Performance va maosh tahlili
print(f"\n3️⃣ Baho va maosh orasidagi bog'lanish:")
performance_salary = df_employees.groupby(
    pd.cut(df_employees['Baho'], bins=[0, 2, 3, 4, 5], labels=['Past', 'O\'rta', 'Yaxshi', 'A\'lo'])
)['Maosh'].agg(['count', 'mean']).round(0)
print(performance_salary)

# 4. Shahar bo'yicha tahlil
print(f"\n4️⃣ Shaharlar bo'yicha taqqoslash:")
city_analysis = df_employees.groupby('Shahar').agg({
    'Maosh': 'mean',
    'Yosh': 'mean',
    'ID': 'count'  # Xodimlar soni
}).round(0)
city_analysis.columns = ['O_rtacha_Maosh', 'O_rtacha_Yosh', 'Xodimlar_Soni']
print(city_analysis.sort_values('O_rtacha_Maosh', ascending=False))

# 5. Ta'lim va maosh tahlili
print(f"\n5️⃣ Ta'lim darajasi va maosh:")
education_salary = df_employees.groupby('Ta_lim')['Maosh'].agg(['mean', 'count']).round(0)
print(education_salary.sort_values('mean', ascending=False))

print("\n" + "=" * 70)

## 4. Ma'lumotlarni saqlash va export qilish

Tahlil natijalarini saqlash usullari:

In [ ]:
# Ma'lumotlarni saqlash va export

print("💾 Ma'lumotlarni saqlash")
print("=" * 50)

# 1. CSV ga saqlash
print("1️⃣ CSV formatida saqlash:")
try:
    df_employees.to_csv('sample_data/xodimlar_tahlil.csv', index=False)
    print("✅ Ma'lumotlar CSV formatida saqlandi")
except Exception as e:
    print(f"❌ Xatolik: {e}")

# 2. Filtrlangan ma'lumotlarni saqlash
print("\n2️⃣ Filtrlangan ma'lumotlarni saqlash:")
high_performers = df_employees[df_employees['Baho'] >= 4.0]
print(f"Yuqori baho olgan xodimlar soni: {len(high_performers)}")

try:
    high_performers.to_csv('sample_data/top_performers.csv', index=False)
    print("✅ Top performers CSV da saqlandi")
except Exception as e:
    print(f"❌ Xatolik: {e}")

# 3. JSON formatida saqlash
print("\n3️⃣ JSON formatida saqlash:")
summary_data = {
    'total_employees': len(df_employees),
    'departments': df_employees['Bo_lim'].value_counts().to_dict(),
    'average_salary': df_employees['Maosh'].mean(),
    'average_age': df_employees['Yosh'].mean()
}

import json
try:
    with open('sample_data/summary.json', 'w', encoding='utf-8') as f:
        json.dump(summary_data, f, ensure_ascii=False, indent=2)
    print("✅ Summary JSON da saqlandi")
except Exception as e:
    print(f"❌ Xatolik: {e}")

print(f"\nSummary ma'lumotlari:")
for key, value in summary_data.items():
    if isinstance(value, (int, float)):
        print(f"{key}: {value:.0f}")
    else:
        print(f"{key}: {value}")

print("\n" + "=" * 50)

## 5. Xulosa va keyingi qadamlar

### 🎉 Bu ma'ruzada o'rgangan narsalar:

#### NumPy:
- ✅ **Array yaratish** - zeros, ones, arange, linspace, random
- ✅ **Indexing va Slicing** - elementlarni tanlash va kesish
- ✅ **Matematik operatsiyalar** - vektorlashtirish, broadcasting
- ✅ **Array manipulation** - reshape, transpose, flatten
- ✅ **Statistik funksiyalar** - mean, std, min, max, median

#### Pandas:
- ✅ **Series va DataFrame** - asosiy ma'lumot strukturalari
- ✅ **Ma'lumot yuklash** - CSV, Excel, JSON fayllardan
- ✅ **Indexing va Selecting** - loc, iloc, boolean indexing
- ✅ **Filtering va Querying** - murakkab shartlar, query method
- ✅ **Data Cleaning** - missing values, duplicates
- ✅ **Transformation** - apply, map, string operations
- ✅ **Grouping va Aggregation** - groupby, pivot tables
- ✅ **Merging va Joining** - ma'lumotlarni birlashtirish

#### Real loyiha:
- ✅ **Exploratory Data Analysis (EDA)** - ma'lumotlarni tadqiq qilish
- ✅ **Statistical insights** - korrelyatsiya, trendlar
- ✅ **Business questions** - amaliy savollarni javoblash
- ✅ **Export va saqlash** - natijalarni faylga saqlash

---

### 🚀 Keyingi qadamlar:

1. **Amaliy mashqlar**: `practical.ipynb` da ko'proq mashq qiling
2. **Uy vazifasi**: Real dataset bilan mustaqil tahlil
3. **Visualization**: Matplotlib/Seaborn o'rganing
4. **Advanced pandas**: Multi-index, time series
5. **Machine Learning**: Scikit-learn bilan ML algoritmlari

---

### 📚 Qo'shimcha resurslar:
- [NumPy documentation](https://numpy.org/doc/)
- [Pandas documentation](https://pandas.pydata.org/docs/)
- [Python for Data Analysis book](https://wesmckinney.com/book/)

**Tabriklaymiz! Siz Python da ma'lumotlar tahlilining asoslarini o'rgandingiz! 🎊**